print("Hello world")
print("Merry's cosmetics")
print("신씨가 소리를 질렀다. \"도둑이야\"")
print("C:\\windows")
print("a \t b")
print("what the hell \n\twhat do you want?")
print("오늘은", "일요일")
print("naver", "카카오", "SK", sep=':')
print("naver", "카카오", "SK", sep='/')
print("first", end=""); print(" second")
print(5/3)
print(10/3)